### ISSUE TITLE
好像不能下载了

### ISSUE THREAD

**Issue by dinghmcn** [qingwenwei/ESLPodcaster#1]
你好，
最近好像不能下载了，在线听也不行。

**Comment by weiqingwen** [comment]
你好，谢谢你的关注。
很遗憾ESLPod的免费内容已经停止更新了，我正在寻找别的免费英语播客资源。

**Comment by dinghmcn** [comment]
你好，感谢你的回复；
可惜了，还好以前的都下载；
MyEslPod使用很方便，期待以后新的英语播客资源；
祝 生活愉快，技术更上一层楼；
